// web-vue3/src/components/Desktop.vue
<template>
  <el-dialog
    :model-value="open"
    :title="dialogTitle"
    width="960px"
    draggable
    destroy-on-close
    @opened="onOpened"
    @close="onClose"
  >
    <div style="position:relative;background:#000;line-height:0">
      <canvas ref="canvasEl" style="display:block;max-width:100%" />
    </div>
    <template #footer>
      <el-button :icon="FullScreen" @click="goFullscreen">Fullscreen</el-button>
      <el-button :icon="RefreshRight" @click="requestRefresh">Refresh</el-button>
      <el-button @click="onClose">Close</el-button>
    </template>
  </el-dialog>
</template>

<script>
import { ref, computed, onUnmounted } from 'vue';
import { ElMessage } from 'element-plus';
import { FullScreen, RefreshRight } from '@element-plus/icons-vue';
import { encrypt, decrypt, stripI18n, genRandHex, getBaseURL, hex2ua, ua2hex, str2ua } from '../api/request.js';

// Outgoing frame: [34, 22, 19, 17, 20, 3, len_hi, len_lo, ...encrypted_json]
// Incoming frame: skip first 5 bytes, then byte[0] = op: 0=frame blocks, 2=resize, 3=JSON control
const MAGIC_OUT = [34, 22, 19, 17, 20, 3];

function formatBytes(bytes) {
  if (!bytes) return '0 B';
  const k = 1024, units = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return (Math.round(bytes / Math.pow(k, i) * 100) / 100) + ' ' + (units[i] ?? 'B');
}

export default {
  name: 'Desktop',
  props: {
    device: { type: Object, required: true },
    open:   { type: Boolean, default: false },
  },
  emits: ['cancel'],
  setup(props, { emit }) {
    const canvasEl   = ref(null);
    const bandwidth  = ref(0);
    const fps        = ref(0);
    const resolution = ref('');

    const dialogTitle = computed(() => {
      const guid = props.device.conn ? props.device.conn.slice(0, 8) : '';
      const parts = ['Desktop', '-', `[${guid}]`, props.device.hostname];
      if (resolution.value) parts.push(resolution.value);
      if (bandwidth.value)  parts.push(formatBytes(bandwidth.value) + '/s');
      if (fps.value)        parts.push(`FPS: ${fps.value}`);
      return parts.join(' ');
    });

    let ws = null, ctx = null, canvas = null;
    let secret = null, connected = false;
    let statsTicker = null;
    let frameCount = 0, byteCount = 0, tickCount = 0;

    function sendJSON(obj) {
      if (!connected || !ws) return;
      const body = encrypt(str2ua(JSON.stringify(obj)), secret);
      const buf  = new Uint8Array(body.length + 8);
      buf.set(MAGIC_OUT, 0);
      buf[6] = (body.length >> 8) & 0xff;
      buf[7] =  body.length       & 0xff;
      buf.set(body, 8);
      ws.send(buf);
    }

    function parseBlocks(ab) {
      ab = ab.slice(5);
      const dv = new DataView(ab);
      const op = dv.getUint8(0);

      if (op === 3) {
        handleControlJSON(ab.slice(1));
        return;
      }
      if (op === 2) {
        const w = dv.getUint16(3, false);
        const h = dv.getUint16(5, false);
        if (w && h && canvas) {
          canvas.width  = w;
          canvas.height = h;
          resolution.value = `${w}×${h}`;
        }
        return;
      }
      if (op === 0) {
        frameCount++;
        byteCount += ab.byteLength;
        let offset = 1;
        while (offset < ab.byteLength) {
          const bl = dv.getUint16(offset,      false);
          const it = dv.getUint16(offset +  2, false);
          const dx = dv.getUint16(offset +  4, false);
          const dy = dv.getUint16(offset +  6, false);
          const bw = dv.getUint16(offset +  8, false);
          const bh = dv.getUint16(offset + 10, false);
          const il = bl - 10;
          offset += 12;
          drawBlock(ab.slice(offset, offset + il), it, dx, dy, bw, bh);
          offset += il;
        }
      }
    }

    function drawBlock(ab, type, dx, dy, bw, bh) {
      if (!ctx) return;
      if (type === 0) {
        ctx.putImageData(new ImageData(new Uint8ClampedArray(ab), bw, bh), dx, dy);
      } else {
        createImageBitmap(new Blob([ab]), 0, 0, bw, bh, {
          premultiplyAlpha: 'none', colorSpaceConversion: 'none',
        }).then((ib) => ctx?.drawImage(ib, 0, 0, bw, bh, dx, dy, bw, bh));
      }
    }

    function handleControlJSON(ab) {
      const text = decrypt(ab, secret);
      let pkt;
      try { pkt = JSON.parse(text); } catch { return; }
      if (pkt.act === 'WARN') {
        ElMessage.warning(stripI18n(pkt.msg) || 'Unknown error');
      } else if (pkt.act === 'QUIT') {
        ElMessage.warning(stripI18n(pkt.msg) || 'Unknown error');
        connected = false;
        ws?.close();
      }
    }

    function connect() {
      if (!canvas) return;
      secret = hex2ua(genRandHex(32));
      const url = getBaseURL(true, `api/device/desktop?uuid=${props.device.conn}&secret=${ua2hex(secret)}`);
      ws = new WebSocket(url);
      ws.binaryType = 'arraybuffer';

      ws.onopen = () => {
        connected = true;
        statsTicker = setInterval(() => {
          bandwidth.value = byteCount;
          fps.value = frameCount;
          byteCount = 0; frameCount = 0;
          tickCount++;
          if (tickCount > 10) { tickCount = 0; sendJSON({ act: 'DESKTOP_PING' }); }
        }, 1000);
      };

      ws.onmessage = (e) => parseBlocks(e.data);

      ws.onclose = () => {
        if (connected) { connected = false; ElMessage.warning('Session disconnected'); }
      };

      ws.onerror = () => {
        if (connected) { connected = false; ElMessage.warning('Session disconnected'); }
        else { ElMessage.warning('Connection failed'); }
      };
    }

    function requestRefresh() {
      if (!connected) {
        ctx = canvas?.getContext('2d', { alpha: false });
        if (ctx) ctx.imageSmoothingEnabled = false;
        connect();
      } else {
        sendJSON({ act: 'DESKTOP_SHOT' });
      }
    }

    function goFullscreen() {
      canvasEl.value?.requestFullscreen().catch(() => ElMessage.warning('Failed to enter fullscreen'));
    }

    function onOpened() {
      canvas = canvasEl.value;
      if (!canvas) return;
      ctx = canvas.getContext('2d', { alpha: false });
      ctx.imageSmoothingEnabled = false;
      connect();
    }

    function onClose() {
      clearInterval(statsTicker);
      statsTicker = null;
      if (connected) { connected = false; ws.onclose = null; ws?.close(); }
      ws = null; ctx = null; canvas = null;
      frameCount = byteCount = tickCount = 0;
      emit('cancel');
    }

    onUnmounted(() => {
      clearInterval(statsTicker);
      if (connected) ws?.close();
    });

    return {
      canvasEl, dialogTitle,
      FullScreen, RefreshRight,
      onOpened, onClose, goFullscreen, requestRefresh,
    };
  },
};
</script>

// web/src/components/desktop/desktop.jsx
import React, {useCallback, useEffect, useState} from 'react';
import {encrypt, decrypt, formatSize, genRandHex, getBaseURL, translate, str2ua, hex2ua, ua2hex} from "../../utils/utils";
import i18n from "../../locale/locale";
import DraggableModal from "../modal";
import {Button, message} from "antd";
import {FullscreenOutlined, ReloadOutlined} from "@ant-design/icons";

let ws = null;
let ctx = null;
let conn = false;
let canvas = null;
let secret = null;
let ticker = 0;
let frames = 0;
let bytes = 0;
let ticks = 0;
function ScreenModal(props) {
	const hostname = props.device.hostname;
	let title = i18n.t('DESKTOP.TITLE') +' - ' + hostname;

	const [resolution, setResolution] = useState('0x0');
	const [bandwidth, setBandwidth] = useState(0);
	const [fps, setFps] = useState(0);
	const canvasRef = useCallback((e) => {
		if (e && props.open && !conn && !canvas) {
			secret = hex2ua(genRandHex(32));
			canvas = e;
			initCanvas(canvas);
			construct(canvas);
		}
	}, [props]);
	useEffect(() => {
		if (!props.open) {
			canvas = null;
			if (ws && conn) {
				clearInterval(ticker);
				ws.close();
				conn = false;
			}
		}
	}, [props.open]);

	function initCanvas() {
		if (!canvas) return;
		ctx = canvas.getContext('2d', {alpha: false});
		ctx.imageSmoothingEnabled = false;
	}
	function construct() {
		if (ctx !== null) {
			if (ws !== null && conn) {
				ws.close();
			}
			ws = new WebSocket(getBaseURL(true, `api/device/desktop?device=${props.device.id}&secret=${ua2hex(secret)}`));
			ws.binaryType = 'arraybuffer';
			ws.onopen = () => {
				conn = true;
			}
			ws.onmessage = (e) => {
				parseBlocks(e.data, canvas, ctx);
			};
			ws.onclose = () => {
				if (conn) {
					conn = false;
					message.warn(i18n.t('COMMON.DISCONNECTED'));
				}
			};
			ws.onerror = (e) => {
				console.error(e);
				if (conn) {
					conn = false;
					message.warn(i18n.t('COMMON.DISCONNECTED'));
				} else {
					message.warn(i18n.t('COMMON.CONNECTION_FAILED'));
				}
			};
			clearInterval(ticker);
			ticker = setInterval(() => {
				setBandwidth(bytes);
				setFps(frames);
				bytes = 0;
				frames = 0;
				ticks++;
				if (ticks > 10 && conn) {
					ticks = 0;
					sendData({
						act: 'DESKTOP_PING'
					});
				}
			}, 1000);
		}
	}
	function fullScreen() {
		canvas.requestFullscreen().catch(console.error);
	}
	function refresh() {
		if (canvas && props.open) {
			if (!conn) {
				initCanvas(canvas);
				construct(canvas);
			} else {
				sendData({
					act: 'DESKTOP_SHOT'
				});
			}
		}
	}

	function parseBlocks(ab, canvas, canvasCtx) {
		ab = ab.slice(5);
		let dv = new DataView(ab);
		let op = dv.getUint8(0);
		if (op === 3) {
			handleJSON(ab.slice(1));
			return;
		}
		if (op === 2) {
			let width = dv.getUint16(3, false);
			let height = dv.getUint16(5, false);
			if (width === 0 || height === 0) return;
			canvas.width = width;
			canvas.height = height;
			setResolution(`${width}x${height}`);
			return;
		}
		if (op === 0) frames++;
		bytes += ab.byteLength;
		let offset = 1;
		while (offset < ab.byteLength) {
			let bl = dv.getUint16(offset + 0, false); // body length
			let it = dv.getUint16(offset + 2, false); // image type
			let dx = dv.getUint16(offset + 4, false); // image block x
			let dy = dv.getUint16(offset + 6, false); // image block y
			let bw = dv.getUint16(offset + 8, false); // image block width
			let bh = dv.getUint16(offset + 10, false); // image block height
			let il = bl - 10; // image length
			offset += 12;
			updateImage(ab.slice(offset, offset + il), it, dx, dy, bw, bh, canvasCtx);
			offset += il;
		}
		dv = null;
	}
	function updateImage(ab, it, dx, dy, bw, bh, canvasCtx) {
		switch (it) {
			case 0:
				canvasCtx.putImageData(new ImageData(new Uint8ClampedArray(ab), bw, bh), dx, dy, 0, 0, bw, bh);
				break;
			case 1:
				createImageBitmap(new Blob([ab]), 0, 0, bw, bh, {
					premultiplyAlpha: 'none',
					colorSpaceConversion: 'none'
				}).then((ib) => {
					canvasCtx.drawImage(ib, 0, 0, bw, bh, dx, dy, bw, bh);
				});
				break;
		}
	}
	function handleJSON(ab) {
		let data = decrypt(ab, secret);
		try {
			data = JSON.parse(data);
		} catch (_) {}
		if (data?.act === 'WARN') {
			message.warn(data.msg ? translate(data.msg) : i18n.t('COMMON.UNKNOWN_ERROR'));
			return;
		}
		if (data?.act === 'QUIT') {
			message.warn(data.msg ? translate(data.msg) : i18n.t('COMMON.UNKNOWN_ERROR'));
			conn = false;
			ws.close();
		}
	}

	function sendData(data) {
		if (conn) {
			let body = encrypt(str2ua(JSON.stringify(data)), secret);
			let buffer = new Uint8Array(body.length + 8);
			buffer.set(new Uint8Array([34, 22, 19, 17, 20, 3]), 0);
			buffer.set(new Uint8Array([body.length >> 8, body.length & 0xFF]), 6);
			buffer.set(body, 8);
			ws.send(buffer);
		}
	}

	return (
		<DraggableModal
			draggable={true}
			maskClosable={false}
			destroyOnClose={true}
			modalTitle={`${title} ${resolution} ${formatSize(bandwidth)}/s FPS: ${fps}`}
			footer={null}
			height={480}
			width={940}
			bodyStyle={{
				padding: 0
			}}
			{...props}
		>
			<canvas
				id='painter'
				ref={canvasRef}
				style={{width: '100%', height: '100%'}}
			/>
			<Button
				style={{right:'59px'}}
				className='header-button'
				icon={<FullscreenOutlined />}
				onClick={fullScreen}
			/>
			<Button
				style={{right:'115px'}}
				className='header-button'
				icon={<ReloadOutlined />}
				onClick={refresh}
			/>
		</DraggableModal>
	);
}

export default ScreenModal;
